name: Telecom_Customer_Churn Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Telecom SVM Model
        run: |
          python model/train_svm.py

      - name: Evaluate Telecom SVM Model
        run: |
          python model/evaluate_svm.py

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests
